[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
optimizer = true
optimizer_runs = 10000

[etherscan]
wchain = { key = "verifyContract", chain = 171717, url = 'https://scan.w-chain.com/api' }
wchain-test = { key = "verifyContract", chain = 71117, url = 'https://scan-testnet.w-chain.com/api' }
base = { key = "${API_KEY_ETHERSCAN}", chain = 8453, url = "https://api.etherscan.io/v2/api?chainid=8453" }

[rpc_endpoints]
wchain = "https://rpc.w-chain.com"
wchain-test = "https://rpc-testnet.w-chain.com"
base = "https://base-pokt.nodies.app"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
